TARGET_NAME=tinyos-reborn
TARGET_BIN_DIR=target/i686-freestanding/debug/
BOOTLOADER_DIR=x86_64-bootloader
BOOTLOADER_BOOT_DIR=$BOOTLOADER_DIR/disk/boot
BOOTLOADER_OPTIONS_TXT=$BOOTLOADER_BOOT_DIR/options.txt
BOOTLOADER_BOOT_BINARY_NAME=kernel.elf
BOOTLOADER_BOOT_BINARY_PATH=$BOOTLOADER_BOOT_DIR/$BOOTLOADER_BOOT_BINARY_NAME

cp $TARGET_BIN_DIR/$TARGET_NAME $BOOTLOADER_BOOT_BINARY_PATH
cat <<EOF > $BOOTLOADER_OPTIONS_TXT
boot_binary=/boot/$BOOTLOADER_BOOT_BINARY_NAME
EOF

if [ -z "$DEBUG" ]; then
  make -C $BOOTLOADER_DIR clean qemu
else
  make -C $BOOTLOADER_DIR clean qemu-debug-32
fi
